### ISSUE TITLE
AttributeError: __enter__ for example from readme

### ISSUE THREAD

**Issue by rubenhorn** [torpyorg/torpy#17]
**What I did:**
```
from torpy import TorClient

hostname = 'ifconfig.me'  # It's possible use onion hostname here as well
with TorClient() as tor:
    # Choose random guard node and create 3-hops circuit
    with tor.create_circuit(3) as circuit:
        # Create tor stream to host
        with circuit.create_stream((hostname, 80)) as stream:
            # Now we can communicate with host
            stream.send(b'GET / HTTP/1.0\r\nHost: %s\r\n\r\n' % hostname.encode())
            recv = stream.recv(1024)
```

**What happened:**
`AttributeError: __enter__`

**Platform:**
Windows 10 Home 64bit, Python 3.7.0

**Comment by jbrown299** [comment]
Which version torpy you use?

You probably using torpy 1.1.3 (installed from pypi https://pypi.org/project/torpy/) and trying examples from master branch (which 1.1.4 version that not uploaded to pypi). Will release 1.1.4 soon and fix this inconsistency.

**Comment by jbrown299** [comment]
torpy v1.1.4 uploaded to pypi now
