### ISSUE TITLE
How to connect to socket server with TorPy?

### ISSUE THREAD

**Issue by RealKevinApetrei** [torpyorg/torpy#21]
How do I connect to a socket server with TorPy also being able to send and receive data as you would when normally working with socket?

**Comment by jbrown299** [comment]
You can find examples in tests https://github.com/torpyorg/torpy/blob/master/tests/integration/test_integration.py. As simple as:
```python
with TorClient() as tor:
    with tor.create_circuit(3) as circuit:
        with circuit.create_stream((HOSTNAME, PORT)) as stream:
            stream.send(b'...')
            data = stream.recv(1024)
```

**Comment by ProtDos** [comment]
Hey, is there any update? For me it doesn't work. Can anyone help connecting to a socket server?

**Comment by ProtDos** [comment]
> You can find examples in tests https://github.com/torpyorg/torpy/blob/master/tests/integration/test_integration.py. As simple as:
> 
> ```python
> with TorClient() as tor:
>     with tor.create_circuit(3) as circuit:
>         with circuit.create_stream((HOSTNAME, PORT)) as stream:
>             stream.send(b'...')
>             data = stream.recv(1024)
> ```

Does that work with `socket.socket(**etc)`? Because for me it doesn't.
