### ISSUE TITLE
How can i set my own proxy first

### ISSUE THREAD

**Issue by caryyu** [torpyorg/torpy#29]
Since connecting to Guard Node is the first step, is there any way that I can make this cli connect my local proxy first and then hop to Tor nodes, thanks

**Comment by Artucuno** [comment]
I also need proxy support for torpy im experimenting with PySocks to set the default proxy (failed). So now I will try to modify the cli proxy to support proxies.

**Comment by Artucuno** [comment]
Unsuccessful. Hopefully if they update it again they can add proxy support and V3

**Comment by caryyu** [comment]
Found out a workaround by https://github.com/rofl0r/proxychains-ng, hope this can help anyone who has the same question here, the simple usage is:

```shell
proxychains4 -q -f ~/.proxychains-tor.conf curl https://ip.me
```
