### ISSUE TITLE
v2 Deprecation

### ISSUE THREAD

**Issue by Artucuno** [torpyorg/torpy#31]
When will V3 support be available, Tor has updated the start page saying that V2 will be gone soon.

**Comment by jbrown299** [comment]
Duplicate of https://github.com/torpyorg/torpy/issues/15

**Comment by SafwanLjd** [comment]
Late answer to the v3 question: it lives in torquests now. Speaks the Tor protocol in Python, does v3 hidden services, and you call it the way you would call requests. https://github.com/SafwanLjd/torquests
