### ISSUE TITLE
Running Torpy as Tor instance with ControlPort

### ISSUE THREAD

**Issue by ghost** [torpyorg/torpy#33]
Hello, I'm new here and after a few days digging the project I feel I didn't really understand if it is possible to run tropy as tor instance with control port set.
Thank you in advance!

**Comment by jbrown299** [comment]
If you need control port you can use official tor implementation: https://www.torproject.org

**Comment by ghost** [comment]
@jbrown299 hello, I would love to not use Control Port, yet I do not understand how to start tor instance with Torpy. Is there a way to run a hidden service using Torpy?
