### ISSUE TITLE
cant acces torpy_socks / torpy_cli

### ISSUE THREAD

**Issue by ThomasEH2005** [torpyorg/torpy#34]
Hello. i want to use the torpy_socks funktion but i cant get it working. I always get a "command not found", i dont know why. maby i just make a dumb misstake. please help me out.

Thanks

**Comment by raddup** [comment]
you need to install with pip, otherwise you need to set path to cli wich is
located in scripts

**Comment by jbrown299** [comment]
not a bug

**Comment by ThomasEH2005** [comment]
i installed it with pip on several systems but i cant get it to work
