### ISSUE TITLE
V3 support?

### ISSUE THREAD

**Issue by abdallahalsalmi** [torpyorg/torpy#35]
As you know V2 is discontinued so any plans for v3 integration?

**Comment by jbrown299** [comment]
Duplicate https://github.com/torpyorg/torpy/issues/15

**Comment by SafwanLjd** [comment]
If you still need v3 after all this time, torquests does it. Written in Python, no Tor binary to run alongside it, and the interface mirrors requests. https://github.com/SafwanLjd/torquests
