### ISSUE TITLE
V3 Support

### ISSUE THREAD

**Issue by Artucuno** [torpyorg/torpy#36]
Hey, I was wondering if you were any close to adding a V3 implementation or if you are still working on this project.

Thanks,
Artucuno

**Comment by jbrown299** [comment]
Duplicate https://github.com/torpyorg/torpy/issues/15

**Comment by SafwanLjd** [comment]
For folks landing here: v3 onion services are working over in torquests. Pure Python client, requests-shaped API, nothing to compile. https://github.com/SafwanLjd/torquests
